/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CapabilityRegistry {
  export type CapabilityStruct = {
    creator: AddressLike;
    bond: BigNumberish;
    capabilityType: BytesLike;
    metadataCID: string;
    certified: boolean;
    slashed: boolean;
  };

  export type CapabilityStructOutput = [
    creator: string,
    bond: bigint,
    capabilityType: string,
    metadataCID: string,
    certified: boolean,
    slashed: boolean
  ] & {
    creator: string;
    bond: bigint;
    capabilityType: string;
    metadataCID: string;
    certified: boolean;
    slashed: boolean;
  };
}

export interface CapabilityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "capabilitiesByType"
      | "capabilityTypeOf"
      | "certifier"
      | "certifyCapability"
      | "getApproved"
      | "getCapabilitiesByType"
      | "getCapability"
      | "isApprovedForAll"
      | "name"
      | "owner"
      | "ownerOf"
      | "registerCapabilityEth"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setCertifier"
      | "slashCapability"
      | "slashedEthPool"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "withdrawBond"
      | "withdrawEthPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BondWithdrawn"
      | "CapabilityCertified"
      | "CapabilityRegistered"
      | "CapabilitySlashed"
      | "EthPoolWithdrawn"
      | "OwnershipTransferred"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "capabilitiesByType",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "capabilityTypeOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "certifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "certifyCapability",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapabilitiesByType",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapability",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCapabilityEth",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCertifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashCapability",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashedEthPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthPool",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "capabilitiesByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "capabilityTypeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "certifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certifyCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapabilitiesByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCapabilityEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCertifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashedEthPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthPool",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondWithdrawnEvent {
  export type InputTuple = [
    capabilityId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [capabilityId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    capabilityId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityCertifiedEvent {
  export type InputTuple = [capabilityId: BigNumberish, certifier: AddressLike];
  export type OutputTuple = [capabilityId: bigint, certifier: string];
  export interface OutputObject {
    capabilityId: bigint;
    certifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityRegisteredEvent {
  export type InputTuple = [capabilityId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [capabilityId: bigint, creator: string];
  export interface OutputObject {
    capabilityId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilitySlashedEvent {
  export type InputTuple = [capabilityId: BigNumberish, penalty: BigNumberish];
  export type OutputTuple = [capabilityId: bigint, penalty: bigint];
  export interface OutputObject {
    capabilityId: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthPoolWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CapabilityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CapabilityRegistry;
  waitForDeployment(): Promise<this>;

  interface: CapabilityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  capabilitiesByType: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  capabilityTypeOf: TypedContractMethod<
    [capabilityId: BigNumberish],
    [string],
    "view"
  >;

  certifier: TypedContractMethod<[], [string], "view">;

  certifyCapability: TypedContractMethod<
    [capabilityId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCapabilitiesByType: TypedContractMethod<
    [capabilityType: BytesLike],
    [bigint[]],
    "view"
  >;

  getCapability: TypedContractMethod<
    [capabilityId: BigNumberish],
    [CapabilityRegistry.CapabilityStructOutput],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  registerCapabilityEth: TypedContractMethod<
    [capabilityType: BytesLike, metadataCID: string],
    [bigint],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setCertifier: TypedContractMethod<[c: AddressLike], [void], "nonpayable">;

  slashCapability: TypedContractMethod<
    [capabilityId: BigNumberish, penalty: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  slashedEthPool: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawBond: TypedContractMethod<
    [capabilityId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawEthPool: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "capabilitiesByType"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "capabilityTypeOf"
  ): TypedContractMethod<[capabilityId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "certifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certifyCapability"
  ): TypedContractMethod<[capabilityId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCapabilitiesByType"
  ): TypedContractMethod<[capabilityType: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCapability"
  ): TypedContractMethod<
    [capabilityId: BigNumberish],
    [CapabilityRegistry.CapabilityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerCapabilityEth"
  ): TypedContractMethod<
    [capabilityType: BytesLike, metadataCID: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCertifier"
  ): TypedContractMethod<[c: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashCapability"
  ): TypedContractMethod<
    [capabilityId: BigNumberish, penalty: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashedEthPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawBond"
  ): TypedContractMethod<[capabilityId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEthPool"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BondWithdrawn"
  ): TypedContractEvent<
    BondWithdrawnEvent.InputTuple,
    BondWithdrawnEvent.OutputTuple,
    BondWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityCertified"
  ): TypedContractEvent<
    CapabilityCertifiedEvent.InputTuple,
    CapabilityCertifiedEvent.OutputTuple,
    CapabilityCertifiedEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityRegistered"
  ): TypedContractEvent<
    CapabilityRegisteredEvent.InputTuple,
    CapabilityRegisteredEvent.OutputTuple,
    CapabilityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CapabilitySlashed"
  ): TypedContractEvent<
    CapabilitySlashedEvent.InputTuple,
    CapabilitySlashedEvent.OutputTuple,
    CapabilitySlashedEvent.OutputObject
  >;
  getEvent(
    key: "EthPoolWithdrawn"
  ): TypedContractEvent<
    EthPoolWithdrawnEvent.InputTuple,
    EthPoolWithdrawnEvent.OutputTuple,
    EthPoolWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BondWithdrawn(uint256,address,uint256)": TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;
    BondWithdrawn: TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;

    "CapabilityCertified(uint256,address)": TypedContractEvent<
      CapabilityCertifiedEvent.InputTuple,
      CapabilityCertifiedEvent.OutputTuple,
      CapabilityCertifiedEvent.OutputObject
    >;
    CapabilityCertified: TypedContractEvent<
      CapabilityCertifiedEvent.InputTuple,
      CapabilityCertifiedEvent.OutputTuple,
      CapabilityCertifiedEvent.OutputObject
    >;

    "CapabilityRegistered(uint256,address)": TypedContractEvent<
      CapabilityRegisteredEvent.InputTuple,
      CapabilityRegisteredEvent.OutputTuple,
      CapabilityRegisteredEvent.OutputObject
    >;
    CapabilityRegistered: TypedContractEvent<
      CapabilityRegisteredEvent.InputTuple,
      CapabilityRegisteredEvent.OutputTuple,
      CapabilityRegisteredEvent.OutputObject
    >;

    "CapabilitySlashed(uint256,uint256)": TypedContractEvent<
      CapabilitySlashedEvent.InputTuple,
      CapabilitySlashedEvent.OutputTuple,
      CapabilitySlashedEvent.OutputObject
    >;
    CapabilitySlashed: TypedContractEvent<
      CapabilitySlashedEvent.InputTuple,
      CapabilitySlashedEvent.OutputTuple,
      CapabilitySlashedEvent.OutputObject
    >;

    "EthPoolWithdrawn(address,uint256)": TypedContractEvent<
      EthPoolWithdrawnEvent.InputTuple,
      EthPoolWithdrawnEvent.OutputTuple,
      EthPoolWithdrawnEvent.OutputObject
    >;
    EthPoolWithdrawn: TypedContractEvent<
      EthPoolWithdrawnEvent.InputTuple,
      EthPoolWithdrawnEvent.OutputTuple,
      EthPoolWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
