/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationOracleNetwork {
  export type CompletionStruct = {
    agent: AddressLike;
    taskType: BytesLike;
    resultCID: string;
    timestamp: BigNumberish;
    challenged: boolean;
    disputed: boolean;
  };

  export type CompletionStructOutput = [
    agent: string,
    taskType: string,
    resultCID: string,
    timestamp: bigint,
    challenged: boolean,
    disputed: boolean
  ] & {
    agent: string;
    taskType: string;
    resultCID: string;
    timestamp: bigint;
    challenged: boolean;
    disputed: boolean;
  };
}

export interface ReputationOracleNetworkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_BOND"
      | "attestCompletion"
      | "challengeCompletion"
      | "challenges"
      | "completionCount"
      | "completions"
      | "disputeCount"
      | "getCompletion"
      | "getSelfAttestScore"
      | "nextCompletionId"
      | "owner"
      | "renounceOwnership"
      | "resolveChallenge"
      | "slashedEthPool"
      | "transferOwnership"
      | "withdrawEthPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeResolved"
      | "ChallengeSubmitted"
      | "EthPoolWithdrawn"
      | "OwnershipTransferred"
      | "SelfAttested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestCompletion",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeCompletion",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "challenges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompletion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelfAttestScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCompletionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveChallenge",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "slashedEthPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthPool",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelfAttestScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCompletionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashedEthPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthPool",
    data: BytesLike
  ): Result;
}

export namespace ChallengeResolvedEvent {
  export type InputTuple = [completionId: BigNumberish, upheld: boolean];
  export type OutputTuple = [completionId: bigint, upheld: boolean];
  export interface OutputObject {
    completionId: bigint;
    upheld: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeSubmittedEvent {
  export type InputTuple = [
    completionId: BigNumberish,
    challenger: AddressLike
  ];
  export type OutputTuple = [completionId: bigint, challenger: string];
  export interface OutputObject {
    completionId: bigint;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthPoolWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SelfAttestedEvent {
  export type InputTuple = [
    completionId: BigNumberish,
    agent: AddressLike,
    taskType: BytesLike
  ];
  export type OutputTuple = [
    completionId: bigint,
    agent: string,
    taskType: string
  ];
  export interface OutputObject {
    completionId: bigint;
    agent: string;
    taskType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationOracleNetwork extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationOracleNetwork;
  waitForDeployment(): Promise<this>;

  interface: ReputationOracleNetworkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_BOND: TypedContractMethod<[], [bigint], "view">;

  attestCompletion: TypedContractMethod<
    [taskType: BytesLike, resultCID: string],
    [bigint],
    "nonpayable"
  >;

  challengeCompletion: TypedContractMethod<
    [completionId: BigNumberish, evidenceCID: string],
    [void],
    "payable"
  >;

  challenges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        challenger: string;
        evidenceCID: string;
        timestamp: bigint;
        resolved: boolean;
      }
    ],
    "view"
  >;

  completionCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  completions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean, boolean] & {
        agent: string;
        taskType: string;
        resultCID: string;
        timestamp: bigint;
        challenged: boolean;
        disputed: boolean;
      }
    ],
    "view"
  >;

  disputeCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getCompletion: TypedContractMethod<
    [completionId: BigNumberish],
    [ReputationOracleNetwork.CompletionStructOutput],
    "view"
  >;

  getSelfAttestScore: TypedContractMethod<
    [agent: AddressLike],
    [
      [bigint, bigint, bigint] & {
        completionCount_: bigint;
        disputeCount_: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  nextCompletionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveChallenge: TypedContractMethod<
    [completionId: BigNumberish, upheld: boolean],
    [void],
    "nonpayable"
  >;

  slashedEthPool: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawEthPool: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attestCompletion"
  ): TypedContractMethod<
    [taskType: BytesLike, resultCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "challengeCompletion"
  ): TypedContractMethod<
    [completionId: BigNumberish, evidenceCID: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        challenger: string;
        evidenceCID: string;
        timestamp: bigint;
        resolved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "completions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean, boolean] & {
        agent: string;
        taskType: string;
        resultCID: string;
        timestamp: bigint;
        challenged: boolean;
        disputed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputeCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCompletion"
  ): TypedContractMethod<
    [completionId: BigNumberish],
    [ReputationOracleNetwork.CompletionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSelfAttestScore"
  ): TypedContractMethod<
    [agent: AddressLike],
    [
      [bigint, bigint, bigint] & {
        completionCount_: bigint;
        disputeCount_: bigint;
        score: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCompletionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveChallenge"
  ): TypedContractMethod<
    [completionId: BigNumberish, upheld: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashedEthPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEthPool"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChallengeResolved"
  ): TypedContractEvent<
    ChallengeResolvedEvent.InputTuple,
    ChallengeResolvedEvent.OutputTuple,
    ChallengeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeSubmitted"
  ): TypedContractEvent<
    ChallengeSubmittedEvent.InputTuple,
    ChallengeSubmittedEvent.OutputTuple,
    ChallengeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EthPoolWithdrawn"
  ): TypedContractEvent<
    EthPoolWithdrawnEvent.InputTuple,
    EthPoolWithdrawnEvent.OutputTuple,
    EthPoolWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SelfAttested"
  ): TypedContractEvent<
    SelfAttestedEvent.InputTuple,
    SelfAttestedEvent.OutputTuple,
    SelfAttestedEvent.OutputObject
  >;

  filters: {
    "ChallengeResolved(uint256,bool)": TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;
    ChallengeResolved: TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;

    "ChallengeSubmitted(uint256,address)": TypedContractEvent<
      ChallengeSubmittedEvent.InputTuple,
      ChallengeSubmittedEvent.OutputTuple,
      ChallengeSubmittedEvent.OutputObject
    >;
    ChallengeSubmitted: TypedContractEvent<
      ChallengeSubmittedEvent.InputTuple,
      ChallengeSubmittedEvent.OutputTuple,
      ChallengeSubmittedEvent.OutputObject
    >;

    "EthPoolWithdrawn(address,uint256)": TypedContractEvent<
      EthPoolWithdrawnEvent.InputTuple,
      EthPoolWithdrawnEvent.OutputTuple,
      EthPoolWithdrawnEvent.OutputObject
    >;
    EthPoolWithdrawn: TypedContractEvent<
      EthPoolWithdrawnEvent.InputTuple,
      EthPoolWithdrawnEvent.OutputTuple,
      EthPoolWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SelfAttested(uint256,address,bytes32)": TypedContractEvent<
      SelfAttestedEvent.InputTuple,
      SelfAttestedEvent.OutputTuple,
      SelfAttestedEvent.OutputObject
    >;
    SelfAttested: TypedContractEvent<
      SelfAttestedEvent.InputTuple,
      SelfAttestedEvent.OutputTuple,
      SelfAttestedEvent.OutputObject
    >;
  };
}
