// Human-readable ABIs matching contracts/{ReputationOracleNetwork,CapabilityRegistry}.sol.
// Kept hand-written so the SDK is self-contained (no hardhat artifact coupling).

export const RON_ABI: string[] = [
  "function CHALLENGE_BOND() view returns (uint256)",
  "function CHALLENGE_WINDOW() view returns (uint256)",
  "function CHALLENGE_TIMEOUT() view returns (uint256)",
  "function MAX_URI_LEN() view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function acceptOwnership() returns ()",
  "function transferOwnership(address newOwner) returns ()",
  "function completions(uint256) view returns (address agent, bytes32 taskType, string resultCID, uint64 timestamp, bool challenged, bool disputed, address counterparty, uint64 receiptTimestamp)",
  "function challenges(uint256) view returns (address challenger, string evidenceCID, uint64 timestamp, bool resolved, uint64 deadline, bool contested, string rebuttalCID)",
  "function receiptCID(uint256) view returns (string)",
  "function nextCompletionId() view returns (uint256)",
  "function completionCount(address) view returns (uint64)",
  "function confirmedCount(address) view returns (uint64)",
  "function disputeCount(address) view returns (uint64)",
  "function slashedEthPool() view returns (uint256)",
  "function attestCompletion(bytes32 taskType, string resultCID) returns (uint256)",
  "function attestReceipt(uint256 completionId, string receiptCID) returns ()",
  "function revokeReceipt(uint256 completionId) returns ()",
  "function challengeCompletion(uint256 completionId, string evidenceCID) payable returns ()",
  "function contestChallenge(uint256 completionId, string rebuttalCID) returns ()",
  "function finalizeChallenge(uint256 completionId) returns ()",
  "function resolveChallenge(uint256 completionId, bool upheld) returns ()",
  "function cancelChallenge(uint256 completionId) returns ()",
  "function withdrawEthPool(address payable to, uint256 amount) returns ()",
  "function getSelfAttestScore(address agent) view returns (uint64 completionCount_, uint64 disputeCount_, uint64 score)",
  "function getTwoSidedScore(address agent) view returns (uint64 confirmedCount_, uint64 disputeCount_, uint64 score, uint64 lastActivity_, uint16 decayBps)",
  "function getCreditScore(address agent) view returns (uint64 distinctCounterparties_, uint64 disputeCount_, uint64 score, uint64 lastActivity_, uint16 decayBps)",
  "function distinctCounterparties(address) view returns (uint64)",
  "function counterpartyConfirmations(address, address) view returns (uint64)",
  "function attestCooldown() view returns (uint64)",
  "function lastAttestation(address) view returns (uint64)",
  "function setAttestCooldown(uint64 cooldown) returns ()",
  "function pause() returns ()",
  "function unpause() returns ()",
  "function paused() view returns (bool)",
  "function getScoreDetails(address agent) view returns (uint64 completionCount_, uint64 disputeCount_, uint64 score, uint64 lastActivity_, uint16 decayBps)",
  "function DECAY_GRACE() view returns (uint256)",
  "function DECAY_HORIZON() view returns (uint256)",
  "function BPS_DENOMINATOR() view returns (uint16)",
  "function getCompletion(uint256 completionId) view returns ((address agent, bytes32 taskType, string resultCID, uint64 timestamp, bool challenged, bool disputed, address counterparty, uint64 receiptTimestamp))",
  "function lastActivity(address) view returns (uint64)",
  "function agentMetadataCID(address) view returns (string)",
  "function registerAgent(string metadataCID) returns ()",
  "function getAgentMetadata(address agent) view returns (string)",
  "event SelfAttested(uint256 completionId, address indexed agent, bytes32 taskType)",
  "event ReceiptAttested(uint256 completionId, address indexed agent, address indexed counterparty)",
  "event ReceiptRevoked(uint256 completionId, address indexed counterparty)",
  "event ChallengeSubmitted(uint256 completionId, address indexed challenger)",
  "event ChallengeContested(uint256 completionId, address indexed agent, string rebuttalCID)",
  "event ChallengeResolved(uint256 completionId, bool upheld)",
  "event ChallengeCancelled(uint256 completionId, address indexed challenger)",
  "event EthPoolWithdrawn(address indexed to, uint256 amount)",
  "event AttestCooldownChanged(uint64 cooldown)",
  "event Paused(address account)",
  "event Unpaused(address account)",
  "event AgentRegistered(address indexed agent, string metadataCID)",
  "error NoSuchCompletion()",
  "error AlreadyChallenged()",
  "error WrongChallengeBond(uint256 sent, uint256 required)",
  "error ChallengeNotPending()",
  "error ChallengeWindowOpen()",
  "error ChallengeWindowClosed()",
  "error ChallengeAlreadyContested()",
  "error ChallengeNotTimedOut(uint64 readyAt)",
  "error NotChallenger()",
  "error NotAgent()",
  "error ReceiptNotAllowed()",
  "error AlreadyReceipted()",
  "error NotCounterparty()",
  "error NothingToWithdraw()",
  "error ReentrancyGuardReentrantCall()",
  "error URITooLong(uint256 length)",
  "error OwnableUnauthorizedAccount(address account)",
  "error OwnableInvalidOwner(address owner)",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
];

export const CAPABILITY_REGISTRY_ABI: string[] = [
  "function certifier() view returns (address)",
  "function MAX_URI_LEN() view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function acceptOwnership() returns ()",
  "function transferOwnership(address newOwner) returns ()",
  "function totalSupply() view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function tokenByIndex(uint256 index) view returns (uint256)",
  "function slashedEthPool() view returns (uint256)",
  "function registerCapabilityEth(bytes32 capabilityType, string metadataCID) payable returns (uint256)",
  "function certifyCapability(uint256 capabilityId) returns (bool)",
  "function slashCapability(uint256 capabilityId, uint256 penalty) returns (bool)",
  "function withdrawBond(uint256 capabilityId) returns ()",
  "function withdrawEthPool(address payable to, uint256 amount) returns ()",
  "function getCapability(uint256 capabilityId) view returns ((address creator, uint256 bond, bytes32 capabilityType, string metadataCID, bool certified, bool slashed))",
  "function capabilityTypeOf(uint256 capabilityId) view returns (bytes32)",
  "function getCapabilitiesByType(bytes32 capabilityType) view returns (uint256[])",
  "function pause() returns ()",
  "function unpause() returns ()",
  "function paused() view returns (bool)",
  "function countCapabilitiesByType(bytes32 capabilityType) view returns (uint256)",
  "function getCapabilitiesByTypePaged(bytes32 capabilityType, uint256 offset, uint256 limit) view returns (uint256[])",
  "event CapabilityRegistered(uint256 capabilityId, address indexed creator)",
  "event CapabilityCertified(uint256 capabilityId, address indexed certifier)",
  "event CapabilitySlashed(uint256 capabilityId, uint256 penalty)",
  "event BondWithdrawn(uint256 capabilityId, address indexed to, uint256 amount)",
  "event EthPoolWithdrawn(address indexed to, uint256 amount)",
  "event CertifierChanged(address indexed previousCertifier, address indexed newCertifier)",
  "event Paused(address account)",
  "event Unpaused(address account)",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error URITooLong(uint256 length)",
  "error OwnableUnauthorizedAccount(address account)",
  "error OwnableInvalidOwner(address owner)",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
];